brew "cocoapods"
brew "gh"
brew "node"
brew "starship"
brew "stow"
brew "tmux"
brew "uv"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "android-studio"
cask "codexbar"
cask "flutter"
cask "ghostty"
cask "mactex-no-gui"
